= ForkJoinPoolTest
:toc: left
:sectnums:
:source-highlighter: rouge

// :source-highlighter: highlight.js
// :plantuml: http://localhost:8080/plantuml
// :plantuml-fetch-diagram: true
// :plantuml-size-limit: 8192
// :plantuml: plantuml.com/plantuml
// :diagram-server-url: https://kroki.io/
// :diagram-server-type: kroki_io

== Actions

=== Configuration

[%header,cols="1a,4a"]
|===
| id | value
| *description*
| ForkJoinPoolTest
| *output_filename*
| benchmark_output.json
| *report_filename*
| benchmark_report.html
| *user_class*
| io.tulip.ForkJoinPoolUser
| *user_params*
|
[%header,cols="1a,3a"]
!===
! id ! value 
! *debug* ! True
!===
| *user_actions*
|
[%header,cols="2a,2a,4a"]
!===
! id ! value ! description
! *1* ! FJP:invoke! 
!===
|===

== Contexts

=== Context-1

[%header,cols="1a,2a"]
|===
| id | value 
| *enabled* | True
| *num_users*   | 1024
| *num_threads* | 4
| *user_params*
|
[%header,cols="1a,3a"]
!===
! id ! value 
! *id* ! 0
!===
|===
=== Context-2

[%header,cols="1a,2a"]
|===
| id | value 
| *enabled* | True
| *num_users*   | 1024
| *num_threads* | 4
| *user_params*
|
[%header,cols="1a,3a"]
!===
! id ! value 
! *id* ! 1
!===
|===

== Benchmarks

=== onStart

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 0.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 0
! - 
!===
|===

=== FJP.a

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 300000.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 1
! - 
!===
| *time* 
| 
[%noheader,cols="2a,1a"]
!===
! *warmup_duration1*
! 30 seconds
! *warmup_duration2*
! 10 seconds
! *benchmark_duration*
! 30 seconds
! *benchmark_iterations*
! 3
!===
|===

=== FJP.b

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 0.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 1
! - 
!===
| *time* 
| 
[%noheader,cols="2a,1a"]
!===
! *warmup_duration1*
! 30 seconds
! *warmup_duration2*
! 10 seconds
! *benchmark_duration*
! 30 seconds
! *benchmark_iterations*
! 3
!===
|===

=== onStop

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 0.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 100
! - 
!===
|===

== JSON Configuration File

[source,json,linenums]
----
{
    "actions": {
        "description": "ForkJoinPoolTest", 
        "output_filename": "benchmark_output.json", 
        "report_filename": "benchmark_report.html", 
        "user_class": "io.tulip.ForkJoinPoolUser", 
        "user_params": {
            "debug": true
        }, 
        "user_actions": {
            "1": "FJP:invoke"
        }
    }, 
    "contexts": {
        "Context-1": {
            "enabled": true, 
            "num_users": 1024, 
            "num_threads": 4, 
            "user_params": {
                "id": 0
            }
        }, 
        "Context-2": {
            "enabled": true, 
            "num_users": 1024, 
            "num_threads": 4, 
            "user_params": {
                "id": 1
            }
        }
    }, 
    "benchmarks": {
        "onStart": {
            "save_stats": false, 
            "scenario_actions": [
                {
                    "id": 0
                }
            ]
        }, 
        "FJP.a": {
            "time": {
                "warmup_duration1": 30, 
                "warmup_duration2": 10, 
                "benchmark_duration": 30, 
                "benchmark_iterations": 3
            }, 
            "aps_rate": 300000.0, 
            "scenario_actions": [
                {
                    "id": 1
                }
            ]
        }, 
        "FJP.b": {
            "time": {
                "warmup_duration1": 30, 
                "warmup_duration2": 10, 
                "benchmark_duration": 30, 
                "benchmark_iterations": 3
            }, 
            "scenario_actions": [
                {
                    "id": 1
                }
            ]
        }, 
        "onStop": {
            "save_stats": false, 
            "scenario_actions": [
                {
                    "id": 100
                }
            ]
        }
    }
}
----

== JVM System Properties

* java.vendor: Eclipse Adoptium
* java.version: 25.0.2
* java.runtime.version: 25.0.2+10-LTS
* os.name: Linux
* os.arch: amd64

== JVM Runtime Options

* Option 1: -XX:+UseCompactObjectHeaders
* Option 2: -Xms2g
* Option 3: -Xmx2g
* Option 4: -XX:+UseG1GC
